### ISSUE TITLE
[Java] java.lang.reflect.InaccessibleObjectException on Java 18

### ISSUE THREAD

**Issue by asfimport** [apache/arrow-java#340]
Getting the following stack trace when running on Java 18.

`BaseAllocator` throws this when it calls the `DefaultAllocationManagerFactory`.

```Java

    private ArrowBuf createEmpty() {
        return this.allocationManagerFactory.empty();
    }
```

```java

Caused by: java.lang.RuntimeException: Failed to initialize MemoryUtil.
	at org.apache.arrow.memory.util.MemoryUtil.<clinit>(MemoryUtil.java:136)
	... 20 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field long java.nio.Buffer.address accessible: module java.base does not \"opens java.nio\" to unnamed module @3453e479
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at org.apache.arrow.memory.util.MemoryUtil.<clinit>(MemoryUtil.java:84)
	... 20 more
 
```

**Reporter**: [Daniel Glöckner](https://issues.apache.org/jira/browse/ARROW-16449)
#### Related issues:
- [[Java][CI]: Add support for Java 17 CI process](https://github.com/apache/arrow/issues/31712) (requires)

<sub>**Note**: *This issue was originally created as [ARROW-16449](https://issues.apache.org/jira/browse/ARROW-16449). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by lidavidm** [comment]
We can't solve this without rewriting the memory subsystem (unfortunately). FFM is a better potential solution.
