### ISSUE TITLE
`arrow.enable_null_check_for_get` causes change in the behavior of `VarBinaryVector#getObject`

### ISSUE THREAD

**Issue by aqni** [apache/arrow-java#469]
### Describe the bug, including details regarding any error messages, version, and platform.

- version: 18.1.0
- platform: windows, jdk17

```java
  @Test
  void testVarbinary(){
    try(RootAllocator allocator = new RootAllocator(Long.MAX_VALUE);
        BigIntVector bigIntVector = new BigIntVector("test", allocator);
        VarBinaryVector varBinVector = new VarBinaryVector("test", allocator)){
      bigIntVector.setNull(0);
      bigIntVector.setValueCount(1);
      varBinVector.setNull(0);
      varBinVector.setValueCount(1);
      Assertions.assertNull(bigIntVector.getObject(0));
      Assertions.assertNull(varBinVector.getObject(0));
    }
  }
```

When I set `arrow.enable_null_check_for_get` to true, this test passes. However, when I set `arrow.enable_null_check_for_get` to false, it failed.

```
org.opentest4j.AssertionFailedError: 
Expected :null
Actual   :[B@73e9cf30
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertNull.failNotNull(AssertNull.java:50)
	at org.junit.jupiter.api.AssertNull.assertNull(AssertNull.java:35)
	at org.junit.jupiter.api.AssertNull.assertNull(AssertNull.java:30)
	at org.junit.jupiter.api.Assertions.assertNull(Assertions.java:279)
	at demo.MainTest.testVarbinary(MainTest.java:27)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

Why does BigIntVector's getObject always return null, while VarBinary Vector's getObject has a different behavior?

**Comment by lidavidm** [comment]
Because you've disabled null checking entirely, so VarBinaryVector takes it as an opportunity to skip the null check and return whatever string data happens to be in that slot (even though the slot is meant to be null, it can still have data allocated, though it is probably an empty string). BigIntVector doesn't have that optimization.

**Comment by lidavidm** [comment]
Arguably, in this case, BigIntVector should also be returning non-null.

**Comment by aqni** [comment]
Is there any plan in the future to unify the behavior of `getObject` when arrow.enable_null_check_for_get is set to false?

**Comment by lidavidm** [comment]
Contributions would be welcome. I don't think anyone is actively working on it.
